# Generated by Django 4.1 on 2023-05-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_season',
            field=models.CharField(blank=True, choices=[(1, '春'), (2, '夏'), (3, '秋'), (4, '冬')], db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_size',
            field=models.CharField(blank=True, choices=[(1, 'XS'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'F')], max_length=150, null=True),
        ),
    ]
